@startuml
title Assign technician to service request
Actor ServiceManager
Boundary AppUI
Entity PersonList
Control Controller
Entity ServiceRequest

ServiceManager -> AppUI: AssignTechnician()
AppUI -> PersonList : search(techId)
loop technician not found
    PersonList --> AppUI : technician
end
AppUI -> Controller : assignTechnician(technician)
alt serviceRequest != null
    Controller -> ServiceRequest : setTechnician(technician)
    ServiceRequest --> Controller
    Controller -> AppUI
    AppUI -> ServiceManager

end






@enduml