@startuml
title Assign technician to service request
Actor ServiceManager
Boundary AppUI
Entity PersonList
Control Controller
Entity ServiceRequest

ServiceManager -> AppUI: AssignTechnician()
AppUI -> PersonList : search(techId)
loop technician not found
    PersonList --> AppUI : technician
end
AppUI -> Controller : assignTechnician(technician)
alt serviceRequest != null
    Controller -> ServiceRequest : setTechnician(technician)
else throw Exception
    Controller --> AppUI
end
ServiceRequest --> Controller
Controller --> AppUI
AppUI --> ServiceManager





@enduml