@startuml
Actor ServiceManager
Boundary AppUI
Control Controller
Collections ServiceRequestList

ServiceManager -> AppUI : SearchTechnician()
AppUI -> Controller :  SearchTechnician()
Controller -> ServiceRequestList : SearchTechnician()
ServiceRequestList --> Controller : Technician
Controller --> AppUI : Technician
AppUI --> ServiceManager : Technician
@enduml