@startuml
title SearchServiceRequest
Actor ServiceManager
Boundary AppUI
Control Controller
Collections ServiceRequestList

ServiceManager -> AppUI : searchServiceRequest()
AppUI -> Controller :  searchServiceRequest(requestId)
loop while service request not found
Controller -> ServiceRequestList : searchServiceRequest(requestId)
ServiceRequestList --> Controller : ServiceRequest
Controller --> AppUI : ServiceRequest
AppUI --> ServiceManager : ServiceRequest
end

@enduml