@startuml

service.ui .up.> service.dbHelper : <<use>>
service.ui .up.> service.domain : <<use>>
package "service.dbHelper" {
 abstract class person
 class Client
 class Technician
 abstract class PersonList
 class TechnicianList
 class ClientList
}

package "service.domain" {
 class Controller
 class ServiceRequest
 class ServiceRequestList
 interface IServiceRequestList
}

package "service.ui" {
 interface IUserInterface
 class AppUI
 class ServiceRequestApp
}

package "library"{
class List
class Scanner
class String

@enduml